### ISSUE TITLE
Unable to get @temporalio/nyc-test-coverage working in jest

### ISSUE THREAD

**Issue by bennidhamma** [temporalio/sdk-typescript#852]
### What are you really trying to do?

Trying to get `@temporalio/nyc-test-coverage` working with our typescript temporal jest tests. 

### Describe the bug

After following the instructions in the [package readme](https://github.com/temporalio/sdk-typescript/blob/main/packages/nyc-test-coverage/README.md), no coverage is generated.

### Minimal Reproduction

I've generated a minimal repro draft PR: https://github.com/temporalio/samples-typescript/pull/192

### Environment/Versions

- OS and processor: Linux x86_64
- Temporal Version: 1.1.0
- using temporal test server

**Comment by lorensr** [comment]
Sorry, that's hopefully fixed in https://github.com/temporalio/sdk-typescript/pull/843 , which I can release Tuesday

**Comment by bennidhamma** [comment]
I don't /think/ so? I pulled the repo down, built and linked the nyc-test-coverage package directly in locally and still don't get any workflow coverage in the activities-examples sample project jest tests.

**Comment by bergundy** [comment]
I haven’t tried this package, it was contributed by @vkarpov15.
In the readme he put instructions explaining how to use this with mocha, I’m not sure if it works with jest.

**Comment by bennidhamma** [comment]
@vkarpov15, do you know if nyc-test-coverage works with jest? Any chance you could update the activities-examples sample to work with it?

**Comment by bergundy** [comment]
Looking at how this is used, it seems like it should be supported in jest but I'd test and verify.
@bennidhamma can you explain exactly what steps you took?
Does this work with mocha locally?

**Comment by vkarpov15** [comment]
@bennidhamma we haven't tried it with Jest yet, I'll give it a shot and see if we can get it working.

**Comment by bennidhamma** [comment]
I'll take a look at mocha too!

**Comment by bennidhamma** [comment]
I was able to get it to run and generate output in mocha. But... it doesn't look like the body of the workflow function is being covered:
![image](https://user-images.githubusercontent.com/309808/187309150-6f98c572-2e40-4f6f-86b8-93f8ebb1cad2.png)

![image](https://user-images.githubusercontent.com/309808/187309047-61574bd4-2745-441e-a582-fe797beb1942.png)

**Comment by bennidhamma** [comment]
> @bennidhamma can you explain exactly what steps you took?
1. install `nyc`, and `@temporalio/nyc-test-coverage` (note: I linked nyc-test-coverage from a local build with lib dir)
2. add workflow coverage instrumentation interceptor, sink, and call merge in after function
3. build
4. run `nyc instrument lib lib --in-place`
5. run mocha with `npx nyc --report-dir nyc-cov --reporter lcov --reporter=text-summary mocha "lib/mocha/*.js"`

**Comment by bennidhamma** [comment]
(mocha changes are also in https://github.com/temporalio/samples-typescript/pull/192)

**Comment by bergundy** [comment]
Thanks for looking into this @bennidhamma, I've assigned @vkarpov15 to it for further investigation.

**Comment by vkarpov15** [comment]
@bennidhamma I'm unable to repro. I was thinking maybe there was some issue with using npx in step 5, but that doesn't seem to matter. Below is the output of running the last 3 steps with 8100ddc6c8bbe82d4b3dcfff84ed3721aa130511:

```
$ npm run build

> temporal-activities-examples@0.1.0 build
> tsc --build

$ ./node_modules/.bin/nyc instrument lib lib --in-place
$ npx nyc --report-dir nyc-cov --reporter lcov --reporter=text-summary mocha "lib/mocha/*.js"


  example workflow
    ✓ returns correct result
    ✓ retries one failure
    ✓ bubbles up activity errors


  3 passing (2s)


=============================== Coverage summary ===============================
Statements   : 50% ( 22/44 )
Branches     : 0% ( 0/4 )
Functions    : 30% ( 3/10 )
Lines        : 47.5% ( 19/40 )
================================================================================
$ 

```

Below is a screenshot of the lcov HTML report for `src/workflows.ts` from the `nyc-cov` directory. It does show that `httpWorkflow()` is executed during the tests.

![image](https://user-images.githubusercontent.com/1620265/190690766-063179cb-177a-49ae-ba03-2af321314fa0.png)

My best guess is that you're somehow re-building after manually instrumenting.
